import {colors} from './components/colors';

export const data = {
  topContent: [
    {
      bg: colors.facebook,
      iconSrc: './images/icon-facebook.svg',
      iconAlt: 'facebook icon',
      username: '@nathanf',
      followersQ: '1987',
      followersText: 'Followers',
      arrowSrc: './images/icon-up.svg',
      arrowAlt: 'arrow up',
      statusText: '12 Today',
      statusColor: '',
    },
    {
      bg: colors.twitter,
      iconSrc: './images/icon-twitter.svg',
      iconAlt: 'twitter icon',
      username: '@nathanf',
      followersQ: '1044',
      followersText: 'Followers',
      arrowSrc: './images/icon-up.svg',
      arrowAlt: 'arrow up',
      statusText: '99 Today',
      statusColor: colors.limeGreen
    },
    {
      bg: colors.instagram,
      iconSrc: './images/icon-instagram.svg',
      iconAlt: 'instagram icon',
      username: '@realnathanf',
      followersQ: '11k',
      followersText: 'Followers',
      arrowSrc: './images/icon-up.svg',
      arrowAlt: 'arrow up',
      statusText: '1099 Today',
      statusColor: colors.limeGreen
    },
    {
      bg: colors.youtube,
      iconSrc: './images/icon-youtube.svg',
      iconAlt: 'youtube icon',
      username: 'Nathan F.',
      followersQ: '8239',
      followersText: 'Subscribers',
      arrowSrc: './images/icon-down.svg',
      arrowAlt: 'arrow down',
      statusText: '144 Today',
      statusColor: colors.brightRed,
    },

  ],
  overviewContent: [
    {
      iconSrc: './images/icon-facebook.svg',
      iconAlt: 'facebook icon',
      title: 'Page Views',
      followersQ: '87',
      arrowSrc: './images/icon-up.svg',
      arrowAlt: 'arrow up',
      statusText: '3%',
      statusColor: colors.limeGreen,
    },
    {
      iconSrc: './images/icon-facebook.svg',
      iconAlt: 'facebook icon',
      title: 'Likes',
      followersQ: '52',
      arrowSrc: './images/icon-down.svg',
      arrowAlt: 'arrow down',
      statusText: '2%',
      statusColor: colors.brightRed,
    },
    {
      iconSrc: './images/icon-instagram.svg',
      iconAlt: 'instagram icon',
      title: 'Likes',
      followersQ: '5462',
      arrowSrc: './images/icon-up.svg',
      arrowAlt: 'arrow up',
      statusText: '2257%',
      statusColor: colors.limeGreen,
    },
    {
      iconSrc: './images/icon-instagram.svg',
      iconAlt: 'instagram icon',
      title: 'Profile Views',
      followersQ: '52k',
      arrowSrc: './images/icon-up.svg',
      arrowAlt: 'arrow up',
      statusText: '1375%',
      statusColor: colors.limeGreen,
    },
    {
      iconSrc: './images/icon-twitter.svg',
      iconAlt: 'twitter icon',
      title: 'Retweets',
      followersQ: '117',
      arrowSrc: './images/icon-up.svg',
      arrowAlt: 'arrow up',
      statusText: '303%',
      statusColor: colors.limeGreen,
    },
    {
      iconSrc: './images/icon-twitter.svg',
      iconAlt: 'twitter icon',
      title: 'Likes',
      followersQ: '507',
      arrowSrc: './images/icon-up.svg',
      arrowAlt: 'arrow up',
      statusText: '553%',
      statusColor: colors.limeGreen,
    },
    {
      iconSrc: './images/icon-youtube.svg',
      iconAlt: 'youtube icon',
      title: 'Likes',
      followersQ: '107',
      arrowSrc: './images/icon-down.svg',
      arrowAlt: 'arrow down',
      statusText: '19%',
      statusColor: colors.brightRed,
    },
    {
      iconSrc: './images/icon-youtube.svg',
      iconAlt: 'youtube icon',
      title: 'Total Views',
      followersQ: '1407',
      arrowSrc: './images/icon-down.svg',
      arrowAlt: 'arrow down',
      statusText: '12%',
      statusColor: colors.brightRed,
    },

  ],
}
